### ISSUE TITLE
Binance coin (image) loading not properly

### ISSUE THREAD

**Issue by MichlF** [matteodanelli/MMM-cryptocurrency#110]
```
{
	module: "MMM-cryptocurrency",
	position: "top_right",
	config: {
		apikey: 'e3564503-4e56-431a-8ece-92c17fb02af8',
		apiDelay: 300000, // every 5 mins (10000 api requests per month)
		currency: ['bitcoin', 'ethereum', 'binance-coin', 'neo'],
		conversion: 'USD',
		maximumFractionDigits: 2,
		displayType: 'logo',
		showGraphs: true,
		fontSize: "x-large",
	}
},
```

Looks like:
<img width="216" alt="Unbenannt" src="https://user-images.githubusercontent.com/7805682/151249026-2a55ef27-2104-4c70-954d-27b1fcadac23.PNG">

I.e. order incorrect and image doesn't load.

Image is present in public folder (colored and black-white) and issue is specific to Binance Coin as it doesn't occur for other coins including those cointaining a hypen.

**Comment by matteodanelli** [comment]
Hey, I have fixed with latest release ;) 
Thanks for pointing it out.

**Comment by MichlF** [comment]
Sorry to reopen/reissue. The BNB coin bug is indeed fixed - so thank for thank!!

However, the order within the currency array is still not respected in the order of presentation in the MagicMirror. However, this does not seem like a bug but maybe more of a feature request because it doesn't seem to be the case for any number/combination of coins? Is this intentional?

**Comment by matteodanelli** [comment]
You're right.
I didn't write that but the order is not respected.
At the moment the order is the one that CoinmarketCap returns, which probably is based on the marketCap of that coin.
I can add some configs about that, but I preferred to solve your issues and delay this feature late.
I'd like to ask you if you can open another issue, in order to better keep track of this.
Thank you!
